version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "insecure"
    ports:
      - "33066:3306"
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8081:8080
​
volumes:
  db-vol:
#http://localhost:8081/